# Generated by Django 5.0.3 on 2024-03-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
